---
name: lintrest
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
    paths:
      - '**.go'
      - 'vendor/**'
      - '.github/workflows/**'

jobs:
  lintrest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14.5'
      - run: bash scripts/gogetcookie.sh
      - run: make tools
      - run: GOGC=5 make lintrest
